github.com:
    users:
        Jezapj:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Jezapj
